package com.pieter_jan.kappagrrm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHARACTER".
 */
public class Character implements android.os.Parcelable {

    private Long id;
    private Integer imageId;
    private String name;
    private String description;

    // KEEP FIELDS - put your custom fields here
    public static final Parcelable.Creator<Character> CREATOR = new Parcelable.Creator<Character>() {
        public Character createFromParcel(Parcel in) {
            return new Character(in.readInt(), in.readString(), in.readString());
        }

        public Character[] newArray(int size) {
            return new Character[size];
        }
    };
    // KEEP FIELDS END

    public Character() {
    }

    public Character(Long id) {
        this.id = id;
    }

    public Character(Long id, Integer imageId, String name, String description) {
        this.id = id;
        this.imageId = imageId;
        this.name = name;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getImageId() {
        return imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    public Character(int imageId, String name, String description)
    {
        this.imageId = imageId;
        this.name = name;
        this.description = description;
    }

    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags)
    {
        dest.writeInt(imageId);
        dest.writeString(name);
        dest.writeString(description);
    }
    // KEEP METHODS END

}
