package com.pieter_jan.redditzor.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pieter_jan.redditzor.model.Listing;
import com.pieter_jan.redditzor.model.Post;

import com.pieter_jan.redditzor.model.ListingDao;
import com.pieter_jan.redditzor.model.PostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig listingDaoConfig;
    private final DaoConfig postDaoConfig;

    private final ListingDao listingDao;
    private final PostDao postDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        listingDaoConfig = daoConfigMap.get(ListingDao.class).clone();
        listingDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        listingDao = new ListingDao(listingDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);

        registerDao(Listing.class, listingDao);
        registerDao(Post.class, postDao);
    }
    
    public void clear() {
        listingDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
    }

    public ListingDao getListingDao() {
        return listingDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

}
