package com.bignerdranch.criminalintent.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;
// KEEP INCLUDES END
/**
 * Entity mapped to table "CRIME".
 */
public class Crime {

    private Long id;
    private String title;
    private java.util.Date date;
    private Boolean solved;
    private String suspect;
    private String suspectMail;
    private String photo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Crime() {
    }

    public Crime(Long id) {
        this.id = id;
    }

    public Crime(Long id, String title, java.util.Date date, Boolean solved, String suspect, String suspectMail, String photo) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.solved = solved;
        this.suspect = suspect;
        this.suspectMail = suspectMail;
        this.photo = photo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getSolved() {
        return solved;
    }

    public void setSolved(Boolean solved) {
        this.solved = solved;
    }

    public String getSuspect() {
        return suspect;
    }

    public void setSuspect(String suspect) {
        this.suspect = suspect;
    }

    public String getSuspectMail() {
        return suspectMail;
    }

    public void setSuspectMail(String suspectMail) {
        this.suspectMail = suspectMail;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    // KEEP METHODS - put your custom methods here
    public String getPhotoFilename() {
        return "IMG_" + getId().toString() + ".jpg";
    }
    public Crime(String s) {
        date = new Date();
        solved = false;
    }
    // KEEP METHODS END

}
